-- Hotels table
CREATE TABLE hotels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_hotels_name ON hotels(name);

-- Rooms table
CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id BIGINT NOT NULL,
    number VARCHAR(50) NOT NULL,
    available BOOLEAN DEFAULT TRUE,
    times_booked BIGINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rooms_hotel FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE,
    CONSTRAINT uk_hotel_room_number UNIQUE (hotel_id, number)
);

CREATE INDEX idx_rooms_hotel_id ON rooms(hotel_id);
CREATE INDEX idx_rooms_available ON rooms(available);
CREATE INDEX idx_rooms_times_booked ON rooms(times_booked);

-- Room locks table
CREATE TABLE room_locks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    booking_uid VARCHAR(255) NOT NULL,
    request_id VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_room_locks_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
);

CREATE INDEX idx_room_locks_room_dates ON room_locks(room_id, start_date, end_date);
CREATE INDEX idx_room_locks_request_id ON room_locks(request_id);
CREATE INDEX idx_room_locks_expires_at ON room_locks(expires_at);
